Changes to awsformat-2.1
avnet-iotconnect/iotc-c-lib pull request #24
Opened 2024-02-06 12:02 UTC by MGilhespie

Changes to code since October 2023 should be merged into the awsformat-2.1 branch.

Changes in processing events, fixing issues with fields and field names.
Removed telemetry "cd" variable.
Removed a nesting level of data in telemetry JSON.
Changes to JSON parsing of commands.

2024-02-08 06:54 UTC, wtk-evoirin requested changes
Looks good but;

- Cosmetic issues
- Some unclear things
- One actual issue

Great work :)

2024-02-08 06:54 UTC, wtk-evoirin commented on src/iotconnect_discovery.c
> +	cJSON *json_root = cJSON_Parse(response_data);
Whitespace error

2024-02-08 06:54 UTC, wtk-evoirin commented on src/iotconnect_discovery.c
> +		if (!meta_json) {
Indent is a bit garbloofed here...

2024-02-08 06:54 UTC, wtk-evoirin commented on src/iotconnect_discovery.c
> +#if 0
Is there a particular reason to hide this behind an "if 0"?

Does the old code need to stay visible or be available for reversion later?

In any case, I'd prefer to have a comment explaining that fact and/or use a dsecriptive preproscessor define

(e.g. #if DEPRECATED_PRE_AWS or something)

2024-02-08 06:54 UTC, wtk-evoirin commented on src/iotconnect_discovery.c
> +#if 0
See above

+ messy indentation

2024-02-08 06:54 UTC, wtk-evoirin commented on src/iotconnect_event.c
> +	if (!eventData) return false;
Indent :)

2024-02-08 06:54 UTC, wtk-evoirin commented on src/iotconnect_event.c
> +		cJSON *sw = cJSON_GetObjectItem(ver, "sw");
Indent :D

2024-02-08 06:54 UTC, wtk-evoirin commented on src/iotconnect_event.c
> +        ver = data->data; // AWS and 2.1 we presume...
Comment doesn't add to my understanding of this - what does this mean?

2024-02-08 06:54 UTC, wtk-evoirin commented on src/iotconnect_event.c
> +	j_ack_id = cJSON_GetObjectItemCaseSensitive(data->root, "ack");
Indents %)

2024-02-08 06:54 UTC, wtk-evoirin commented on src/iotconnect_event.c
> +	if (!j_ack_id) return NULL;
Inconsistent null checks (some in curly brackets, some not)

2024-02-08 06:54 UTC, wtk-evoirin commented on src/iotconnect_telemetry.c
> +#if 0
See above about #if 0

+ indents!

2024-02-08 06:54 UTC, wtk-evoirin commented on src/iotconnect_telemetry.c
Missing NULL check for telemetry_data_array?

2024-02-08 10:17 UTC, pywtk approved these changes
No Notes from me

2024-02-12 03:22 UTC, wtk-evoirin commented on src/iotconnect_telemetry.c
> +	//create 2nd d_array in 1st d object
comment here is inaccurate

2024-02-12 03:28 UTC, oerg866 commented on src/iotconnect_discovery.c
>      cJSON *tmp_value = NULL;
This variable is now unused and will throw a warning.

2024-02-12 03:30 UTC, oerg866 commented on src/iotconnect_discovery.c
>                  // Assume parsing eror, but it could alo be (unlikely) allocation error
might as well fix these typos :D

2024-02-13 06:55 UTC, oerg866 commented on src/iotconnect_event.c
> +    cJSON *command = cJSON_GetObjectItemCaseSensitive(data->root, "cmd");
since we set data to root, is this change actually necessary?

2024-02-15 02:04 UTC, wtk-evoirin commented
https://github.com/avnet-iotconnect/iotc-c-lib/blob/a8d6b26cde97099a254a7e254fc9e3bb12862288/src/iotconnect_telemetry.c#L91

Memory leak here!!

2024-02-16 04:59 UTC, wtk-evoirin commented on src/iotconnect_telemetry.c
>      message->current_telemetry_object = d3_object;
Shouldn't this now technically be called d2_object?

2024-02-22 08:19 UTC, nik-markovic requested changes
We ought to be taking in my 2.1 c-lib code. Seems like duplication of effort.

2024-03-27 16:53 UTC, nik-markovic commented
Cosing in favor of the new 2.1 implementation.

2024-03-27 16:53 UTC, closed without merging